# Generated by Django 5.1.1 on 2024-09-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book_app', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='profile',
        ),
        migrations.AddField(
            model_name='book',
            name='profiles',
            field=models.ManyToManyField(to='app_book_app.profile'),
        ),
    ]
