# Generated by Django 5.1.1 on 2024-09-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book_app', '0004_remove_book_profile_book_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='profiles',
            field=models.ManyToManyField(related_name='book_profiles', to='app_book_app.profile'),
        ),
    ]
