# Generated by Django 5.1.1 on 2024-09-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book_app', '0005_alter_book_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='profiles',
            field=models.ManyToManyField(related_name='profile_books', to='app_book_app.profile'),
        ),
    ]
